# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build environment (optional, for specific Python versions or Docker builds)
build:
  os: ubuntu-latest
  tools:
    python: "3.8.10" # Specify the Python version to use for building

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# Python dependencies
python:
   install:
   - requirements: docs/requirements.txt # Point to the requirements.txt inside your docs folder
   # Or if requirements.txt is in project root:
   # - requirements: requirements.txt
   # Or if your Dashboard_App is a package you want to install:
   # - method: pip
   #   path: . # This would install your entire project if it's a package